Repository spyder-ide/spyder-kernels, pull requests merged in 2025-05, with the labels that each got.

#541 PR: Support pathlib and None in namespace view
  spyder_kernels/utils/nsview.py
  spyder_kernels/utils/tests/test_nsview.py
Labels: type:Enhancement

#542 PR: Disable magics and commands to call Python package managers
  spyder_kernels/console/shell.py
  spyder_kernels/console/tests/test_console_kernel.py
Labels: type:Bug

#533 PR Add pixi related utility functions and env info
  spyder_kernels/console/kernel.py
  spyder_kernels/utils/pythonenv.py
Labels: type:Enhancement

#544 PR: Add minimal required version of `traitlets`
  requirements/posix.txt
  requirements/windows.txt
  setup.py
Labels: type:Bug

#545 Backport PR #544 on branch 3.x (PR: Add minimal required version of `traitlets`)
  requirements/posix.txt
  requirements/windows.txt
  setup.py
Labels: type:Bug

#546 PR: Update changelog for 3.0.5
  CHANGELOG.md
  RELEASE.md
Labels: type:Task

#547 Backport PR #546 on branch 3.x (PR: Update changelog for 3.0.5)
  CHANGELOG.md
  RELEASE.md
Labels: type:Task
