Repository spyder-ide/spyder-kernels, pull requests merged in 2025-04, with the labels that each got.

#536 PR: Preserve case sensitivity of working directory when running files
  spyder_kernels/customize/code_runner.py
Labels: type:Bug

#537 Backport PR #536 on branch 3.x (PR: Preserve case sensitivity of working directory when running files)
  spyder_kernels/customize/code_runner.py
Labels: type:Bug

#538 PR: Use Ubuntu 22.04 for testing on CIs because the 20.04 image was removed
  .github/workflows/linux-pip-tests.yml
  .github/workflows/linux-tests.yml
Labels: type:Task

#539 Backport PR #538 on branch 3.x (PR: Use Ubuntu 22.04 for testing on CIs because the 20.04 image was removed)
  .github/workflows/linux-pip-tests.yml
  .github/workflows/linux-tests.yml
Labels: type:Task

#535 PR: Display contents of string arrays
  spyder_kernels/utils/nsview.py
  spyder_kernels/utils/tests/test_nsview.py
Labels: type:Enhancement

#540 PR: Support `frozenset` in namespace view
  spyder_kernels/utils/nsview.py
  spyder_kernels/utils/tests/test_nsview.py
Labels: type:Enhancement
