Repository spyder-ide/spyder-kernels, pull requests merged in 2025-02, with the labels that each got.

#530 PR: Correctly process Pdb commands available in `cmdqueue`
  spyder_kernels/customize/spyderpdb.py
Labels: type:Bug

#531 Backport PR #530 on branch 3.x (PR: Correctly process Pdb commands available in `cmdqueue`)
  spyder_kernels/customize/spyderpdb.py
Labels: type:Bug

#478 PR: Add feature to prepend/append PYTHONPATH to sys.path
  spyder_kernels/console/kernel.py
  spyder_kernels/console/start.py
  spyder_kernels/console/tests/test_console_kernel.py
  spyder_kernels/customize/spydercustomize.py
Labels: type:Enhancement

#532 PR: Split `test_interrupt` into two tests
  spyder_kernels/console/tests/test_console_kernel.py
Labels: type:Task
